# stages > jobs > steps 


trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Job1
  steps:
  - script: echo Job1 Hello world this is my first pipeline but its wont be last!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
- job: Job2
  steps:
  - script: echo Job2 Hello world this is my first pipeline but its wont be last!
    displayName: 'Run a one-line script'